### ISSUE TITLE
pageSize doesn't limit the results for listSecretVersions()

### ISSUE THREAD

**Issue by romaincointepas** [googleapis/nodejs-secret-manager#129]
On version v3.0.0:

```js
const [versions] = await client.listSecretVersions({
  parent: 'projects/1234/secrets/my-secret',
  pageSize: 3,
});
```
returns all versions (instead of just the 3 latest).

For certain key rotations, it is useful to have the last 3 versions of a secret (previous, current, next).

**Comment by stephenplusplus** [comment]
I believe the pageSize option will be mostly unnoticed in this case, as it is an option the upstream API allows us to control how many results come back per “page” (or per API call). Since we are trying to get all results by default, we keep going, in this case 3 at a time. You can disable this behavior with “autoPaginate: false”, and we should stop trying to get more pages after we received the first page with 3 results.

I believe we also have a “maxResults” option that should work, however, I’m not certain it will grab from the end of the list as opposed to the beginning. In that case, you may need to get all of the results, then pop off the last three from the response. I’m not very familiar with this API, but maybe there’s a “filter” option as well that could sort the response?

I can look into this more in the coming days for a more concrete answer, but wanted to provide this information now in case it gives you a head start.

**Comment by romaincointepas** [comment]
Using `maxResults` works (and returns the 3 latest), thanks!

Could we count on this behavior not changing in the future? As in suddenly returning the 3 earliest versions?

**Comment by stephenplusplus** [comment]
> Do you know if it truncates the results locally or it's actually just fetching the latest 3 versions?

I believe it can be both, depending on how it's called. If you set "pageSize: 3" *and* "maxResults: 3", it should only ever pull 3. If you just set "maxResults: 3", it will get whatever size of response the API sent, and then our library only returns 3.

> Also, can we count on this behavior not changing in the future? As in suddenly returning the 3 earliest versions?

I cannot speak to that, unfortunately, as that's up to the upstream API. It could be worth reaching them through their support page: https://cloud.google.com/secret-manager/docs/getting-support

Sorry my response took longer than I expected. Hope this was helpful.
