### ISSUE TITLE
chore: getSecret.js has multiple calls for substantiating variable - breaks sample.

### ISSUE THREAD

**Issue by Intelrunner** [googleapis/nodejs-secret-manager#267]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-secret-manager/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Mac OSX
  - Node.js version: 10, 12, 14
  - npm version:
  - `@google-cloud/secret-manager` version: latest

#### Steps to reproduce

  1. Look at previous code
  2. Replace ALL calls for name variable with necessary secret name. 
  3. Watch NodeJS spit out a nasty reminder you can't setup a const twice.
  4. I have a PR ready for this, with changes, please assign to myself
 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by chingor13** [comment]
Thanks for opening this, but this is intentional. These snippets (code between START/END comments) are imported into cloud.google.com and displayed without the entire file. When copy/pasting from there, it works as intended.

We set the variable name as a function parameter so that we can test these samples using real data to ensure they are working.

If you are starting with the sample file and choose to uncomment out the `const name = '...'` line, you can remove the function parameter that uses the same name.
